### ISSUE TITLE
Battery Level Sensor

### ISSUE THREAD

**Issue by G-Pereira** [ieeeupsb/Dora#13]
Design hardware to read efficiently the battery status (there's ICs in the market for this).
Make sure the solution is appropriate for LiPo batteries.
Battery will be a LiPo 3C 11.1V

**Comment by lm-sousa** [comment]
https://www.digikey.com/product-detail/en/texas-instruments/BQ76925PWR/296-29341-1-ND/2728027

**Comment by JoaoGarrido** [comment]
Datasheet:
http://www.ti.com/lit/ds/symlink/bq76925.pdf
Application notes:
http://www.ti.com/lit/an/slua707/slua707.pdf

Some notes:
- LDO regulator from the IC will not power the MCU(what should i do with it?) 
- Not sure how to do the battery temperature part
