### ISSUE TITLE
Early pick of MCU

### ISSUE THREAD

**Issue by G-Pereira** [ieeeupsb/Dora#16]
At this stage pick a STM32 family of devices by looking at their top level features and pick one with a decent amount of pins to begin planning MCU connections. Don't waste time thinking on the number of I/O in detail.
On the final stages of development the MCU will be revised and sized.
Only make sure to set STM32 family on stone (this is important) in order to avoid wasting time.

**Comment by lm-sousa** [comment]
STM32F4 family
